name: flutter_background_service
description: A flutter plugin for executing dart code continously even application closed.
version: 5.0.5
repository: https://github.com/ekasetiawans/flutter_background_service

funding:
  - https://www.buymeacoffee.com/ekasetiawans

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service_platform_interface:
    git:
      url: https://github.com/uprise-fin/flutter_background_service.git
      path: packages/flutter_background_service_platform_interface
      ref: release/uprise
  flutter_background_service_android:
    git:
      url: https://github.com/uprise-fin/flutter_background_service.git
      path: packages/flutter_background_service_android
      ref: release/uprise
  flutter_background_service_ios:
    git:
      url: https://github.com/uprise-fin/flutter_background_service.git
      path: packages/flutter_background_service_ios
      ref: release/uprise
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: flutter_background_service_android
      ios:
        default_package: flutter_background_service_ios
